---
- name: Destory the resources created
  hosts: localhost
  gather_facts: no
  vars_files:
    - ../vars/change_request.yml
  vars_prompt:
    - name: host
      prompt: ServiceNow URL
      private: false
    - name: username
      prompt: Username
      private: false
    - name: password
      prompt: Password

  tasks:
    - name: Delete change request
      servicenow.itsm.change_request_task:
        instance:
          host: "{{ host }}"
          username: "{{ username }}"
          password: "{{ password }}"
        state: absent
        change_request_number: "{{ change_request_number }}"
        number: "{{ change_request_number }}"
      when: change_request_number is defined
      register: state


    - name: Show the list of Change Task numbers
      debug:
        var: state